// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vn3_FkujEHEb8MoAacW2xklMGa2_hP4',
    appId: '1:364220174080:android:8b8ec8247ef31b1c742de5',
    messagingSenderId: '364220174080',
    projectId: 'smart-cap-754a4',
    databaseURL: 'https://smart-cap-754a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-cap-754a4.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8oYFWySHKOFo6k0uvceO5l6RfPI445w',
    appId: '1:364220174080:web:799575f4eac55fa2742de5',
    messagingSenderId: '364220174080',
    projectId: 'smart-cap-754a4',
    authDomain: 'smart-cap-754a4.firebaseapp.com',
    databaseURL: 'https://smart-cap-754a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-cap-754a4.appspot.com',
    measurementId: 'G-XV57LYRL6K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTIy3F1cnAlYsqfKv6LujsAG-JOo3BLS8',
    appId: '1:364220174080:ios:4c7b318bd3a2b807742de5',
    messagingSenderId: '364220174080',
    projectId: 'smart-cap-754a4',
    databaseURL: 'https://smart-cap-754a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-cap-754a4.appspot.com',
    iosClientId: '364220174080-9qj9qev90foldnaaq66bqa8u4e7l8q8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetoothLowEnergy',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIy3F1cnAlYsqfKv6LujsAG-JOo3BLS8',
    appId: '1:364220174080:ios:4c7b318bd3a2b807742de5',
    messagingSenderId: '364220174080',
    projectId: 'smart-cap-754a4',
    databaseURL: 'https://smart-cap-754a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-cap-754a4.appspot.com',
    iosClientId: '364220174080-9qj9qev90foldnaaq66bqa8u4e7l8q8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetoothLowEnergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP8oYFWySHKOFo6k0uvceO5l6RfPI445w',
    appId: '1:364220174080:web:31d2b940670cb04b742de5',
    messagingSenderId: '364220174080',
    projectId: 'smart-cap-754a4',
    authDomain: 'smart-cap-754a4.firebaseapp.com',
    databaseURL: 'https://smart-cap-754a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-cap-754a4.appspot.com',
    measurementId: 'G-91RPGH71YP',
  );

}